name: Run R Script on Windows

on:
  schedule:
    - cron: "* * * * *"   # corre cada minuto (CRON formato UTC)
  workflow_dispatch:       # permite lanzarlo manualmente

jobs:
  run-r:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('lubridate','dplyr','dtplyr','tidyr','DBI','RMySQL','googlesheets4','gargle','readr','purrr','jsonlite','httr'), repos='https://cran.rstudio.com/')"

      - name: Restore Google credentials
        run: |
          echo "${{ secrets.GCP_JSON }}" > gg-ss-api-token.json

      - name: Run script
        run: |
          Rscript ejercicio.R
